[package]
name = "{{crate-name}}"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
description = "{{project-name}}"
keywords = []
readme = "../../README.md"

[dependencies]
